In [1]:
using Revise, Dates, JSON, DataFrames, BenchmarkTools, StatsBase, Parquet

In [2]:
import Pkg
Pkg.activate(joinpath(@__DIR__, "SlurmCLI"))

  Activating project at `/global/u1/b/blaschke/analyze-iris/SlurmCLI`


In [3]:
using SlurmCLI

┌ Info: Precompiling SlurmCLI [f20ae521-c5a4-4611-9d1a-038c97f73376]
└ @ Base loading.jl:1504


In [4]:
lx31_1  = Reservation(
    name      = "lx31_processing_1",
    nodelist  = "nid00[800-831]",
    starttime = "2021-07-23T10:00:00",
    endtime   = "2021-07-23T22:00:00",
    nodecount = 32,
    features  = "haswell",
    account   = "lcls"
)
lx31_1a = Reservation(
    name      = "lx31_processing_1a",
    nodelist  = "nid0[1161,1203-1205,1330-1332,1393-1403,1423-1426,1454-1460,1463-1464,1492]",
    starttime = "2021-07-23T23:07:19",
    endtime   = "2021-07-24T11:07:19",
    nodecount = 32,
    features  = "haswell",
    account   = "lcls"
)
lx31_2  = Reservation(
    name      = "lx31_processing_2", 
    nodelist  = "nid0[0792,0800-0808,0810-0811,0813-0831,0845,1325-1326,1929-1931,1969,2010,2013,2018,2026-2027,2081-2084,2105-2106,2146-2147,2150-2151,2161,2219,2221-2225,2228,2293-2295]",
    starttime = "2021-07-25T10:00:00", 
    endtime   = "2021-07-26T10:00:00", 
    nodecount = 64,
    features  = "haswell", 
    account   = "lcls"
)

lv07_1  = Reservation(
    name      = "lv07_processing_1",
    nodelist  = "nid00[792-795,800-831,845,847-848,852-876]",
    starttime = "2021-07-29T10:00:00",
    endtime   = "2021-07-29T22:00:00",
    nodecount = 64,
    features  = "haswell",
    account   = "lcls"
)
lv07_2  = Reservation(
    name      = "lv07_processing_2",
    nodelist  = "nid00[792-795,800-831,845,847-848,852-876]",
    starttime = "2021-07-30T10:00:00",
    endtime   = "2021-07-30T22:00:00",
    nodecount = 64,
    features  = "haswell",
    account   = "lcls"
)
lv07_3  = Reservation(
    name      = "lv07_processing_3",
    nodelist  = "nid00[792-795,800-831,845,847-848,852-876]",
    starttime = "2021-07-31T10:00:00",
    endtime   = "2021-07-31T22:00:00",
    nodecount = 64,
    features  = "haswell",
    account   = "lcls")
lv07_4  = Reservation(
    name      = "lv07_processing_4",
    nodelist  = "nid00[792-795,800-831,845,847-848,852-876]",
    starttime = "2021-08-01T10:00:00",
    endtime   = "2021-08-01T22:00:00",
    nodecount = 64,
    features  = "haswell",
    account   = "lcls"
)

p203_1  = Reservation(
    name      = "p203_processing_1",
    nodelist  = "nid00[792-795,800-827]",
    starttime = "2021-08-01T22:00:00",
    endtime   = "2021-08-02T10:00:00",
    nodecount = 32,
    features  = "haswell",
    account   = "lcls"
)
p203_2  = Reservation(
    name      = "p203_processing_2",
    nodelist  = "nid00[792-795,800-827]",
    starttime = "2021-08-02T22:00:00",
    endtime   = "2021-08-03T12:00:00",
    nodecount = 32,
    features  = "haswell",
    account   = "lcls"
)
p203_3  = Reservation(
    name      = "p203_processing_2",
    nodelist  = "nid00[792-795,800-828,860,876-882,884,902-910,913-914,924-926,928-929,935,947-949,952-953]",
    starttime = "2021-08-02T22:00:00",
    endtime   = "2021-08-03T12:00:00",
    nodecount = 64,
    features  = "haswell",
    account   = "lcls"
)

Reservation("p203_processing_2", "nid00[792-795,800-828,860,876-882,884,902-910,913-914,924-926,928-929,935,947-949,952-953]", DateTime("2021-08-02T22:00:00"), DateTime("2021-08-03T12:00:00"), 64, "haswell", "lcls")

In [9]:
sav, status = sacct_collect_jobs(lx31_1, Day(7))
status

1-element Vector{NamedTuple{(:code, :range, :err), Tuple{Int64, Vector{DateTime}, String}}}:
 (code = 0, range = [DateTime("2021-07-23T10:00:00"), DateTime("2021-07-23T22:00:00")], err = "")

In [50]:
sav, status = sacct_collect_jobs("lcls", DateTime("2020-01-01T00:00:00"), DateTime("2022-05-16T00:00:00"), Day(7))
status

Collected: 100%|██████████████████████████| Time: 2:52:32 (83.49  s/it)
  total collected:  18079


124-element Vector{NamedTuple{(:code, :range, :err), Tuple{Int64, Vector{DateTime}, String}}}:
 (code = 0, range = [DateTime("2020-01-01T00:00:00"), DateTime("2020-01-08T00:00:00")], err = "")
 (code = 0, range = [DateTime("2020-01-08T00:00:00"), DateTime("2020-01-15T00:00:00")], err = "")
 (code = 0, range = [DateTime("2020-01-15T00:00:00"), DateTime("2020-01-22T00:00:00")], err = "")
 (code = 0, range = [DateTime("2020-01-22T00:00:00"), DateTime("2020-01-29T00:00:00")], err = "")
 (code = 0, range = [DateTime("2020-01-29T00:00:00"), DateTime("2020-02-05T00:00:00")], err = "")
 (code = 0, range = [DateTime("2020-02-05T00:00:00"), DateTime("2020-02-12T00:00:00")], err = "")
 (code = 0, range = [DateTime("2020-02-12T00:00:00"), DateTime("2020-02-19T00:00:00")], err = "")
 (code = 0, range = [DateTime("2020-02-19T00:00:00"), DateTime("2020-02-26T00:00:00")], err = "")
 (code = 0, range = [DateTime("2020-02-26T00:00:00"), DateTime("2020-03-04T00:00:00")], err = "")
 (code = 0, range = [Da

In [54]:
filter(x->x.code>0, status)

NamedTuple{(:code, :range, :err), Tuple{Int64, Vector{DateTime}, String}}[]

In [53]:
open(joinpath("data", "sacct", "cori_jobs_2020_2022.json"), "w") do f
    JSON.print(f, sav, 4)
end

In [73]:
column_names, df_columns = get_column_descriptors(sav)

(["endTime", "workingDirectory", "stdinPath", "packJobOffset", "submitTime", "gresUsed", "features", "startTime", "jobDerivedExitCode", "licenses"  …  "nodes", "arrayJobId", "timeLimit", "argv", "allocCpus", "reservation", "burstBuffer", "partition", "tresRequest", "sdn"], Set(Tuple{String, DataType}[("endTime", Int64), ("workingDirectory", String), ("stdinPath", String), ("packJobOffset", Int64), ("submitTime", Int64), ("gresUsed", String), ("features", String), ("startTime", Int64), ("jobDerivedExitCode", Int64), ("licenses", String)  …  ("nodes", String), ("arrayJobId", Int64), ("timeLimit", Int64), ("argv", Vector{Any}), ("allocCpus", Int64), ("reservation", String), ("burstBuffer", String), ("partition", String), ("tresRequest", String), ("sdn", String)]))

In [93]:
df[2, :]["jobId"]

27698103

In [90]:
df, merged = to_dataframe(sav)
df

Merging: 100%|████████████████████████████| Time: 0:05:35 (18.55 ms/it)


18079×42 DataFrame
   Row │ allocCpus  allocNodes  arrayJobId  arrayTaskId  batchHost  cluster  e ⋯
       │ Int64      Int64       Int64       Int64        String?    String   I ⋯
───────┼────────────────────────────────────────────────────────────────────────
     1 │      4352          16           0           -2  nid02440   cori     1 ⋯
     2 │         0           0           0           -2  missing    cori     1
     3 │        64           1           0           -2  nid00090   cori     1
     4 │        64           1           0           -2  nid00728   cori     1
     5 │        64           1           0           -2  nid00729   cori     1 ⋯
     6 │      1344          21           0           -2  nid00029   cori     1
     7 │      1344          21           0           -2  nid00143   cori     1
     8 │      1344          21           0           -2  nid00100   cori     1
     9 │      1344          21           0           -2  nid00100   cori     1 ⋯
    10 │        64           1           0           -2  nid00523   cori     1
    11 │        64           1           0           -2  nid00523   cori     1
   ⋮   │     ⋮          ⋮           ⋮            ⋮           ⋮         ⋮       ⋱
 18070 │        64           1           0   4294967294  nid00028   cori     1
 18071 │        64           1           0   4294967294  nid00222   cori     1 ⋯
 18072 │        64           1           0   4294967294  nid00020   cori     1
 18073 │        64           1           0   4294967294  nid00021   cori     1
 18074 │        64           1           0   4294967294  nid00242   cori     1
 18075 │         0           0           0   4294967294  missing    cori     1 ⋯
 18076 │         0           0           0   4294967294  missing    cori     1
 18077 │         0           0           0   4294967294  missing    cori     1
 18078 │         0           0           0   4294967294  missing    cori     1
 18079 │        64           1           0   4294967294  nid00248   cori     1 ⋯
                                               36 columns and 18058 rows omitted

In [88]:
cm = countmap(df.jobId)
filter(x->(cm[x]!=1), df.jobId)

Int64[]

In [89]:
write_parquet("test.parquet", df_sav)

4

In [70]:
@show map(x->x["merged_names"], merged)

map((x->begin
            #= In[70]:1 =#
            x["merged_names"]
        end), merged) = [["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["argv"], ["ar

112-element Vector{Vector{String}}:
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ⋮
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]
 ["argv"]

In [87]:
function find_diffs(x)
    contain_diffs = String[]
    for name in names(x)
        col = x[:, name]
        if length(unique(col)) > 1
            push!(contain_diffs, name)
        end
    end
    contain_diffs
end

find_diffs (generic function with 1 method)

In [88]:
find_diffs(df_sav[df_sav.jobId .== 44405291, :])

1-element Vector{String}:
 "argv"

In [89]:
df_sav[df_sav.jobId .== 44405291, "argv"]

2-element Vector{Any}:
 "/global/u1/v/vpa/project/jpt_no" ⋯ 76 bytes ⋯ "ptfcn/run_3ptfcn/batch_3ptcn.sh"
 "9"

In [90]:
filter(x->x["jobId"] == 44405291, sav)[1]["argv"]

2-element Vector{Any}:
 "/global/u1/v/vpa/project/jpt_no" ⋯ 76 bytes ⋯ "ptfcn/run_3ptfcn/batch_3ptcn.sh"
 "9"

In [91]:
find_diffs(df_sav[df_sav.jobId .== 44405349, :])

1-element Vector{String}:
 "argv"

In [92]:
df_sav[df_sav.jobId .== 44405349, "argv"]

2-element Vector{Any}:
 "/global/u1/v/vpa/project/jpt_no" ⋯ 76 bytes ⋯ "ptfcn/run_3ptfcn/batch_3ptcn.sh"
 "0"

In [93]:
find_diffs(df_sav[df_sav.jobId .== 44405355, :])

1-element Vector{String}:
 "argv"

In [94]:
df_sav[df_sav.jobId .== 44405355, "argv"]

2-element Vector{Any}:
 "/global/u1/v/vpa/project/jpt_no" ⋯ 76 bytes ⋯ "ptfcn/run_3ptfcn/batch_3ptcn.sh"
 "3"

In [95]:
find_diffs(df_sav[df_sav.jobId .== 44428415, :])

1-element Vector{String}:
 "argv"

In [96]:
df_sav[df_sav.jobId .== 44428415, "argv"]

7-element Vector{Any}:
 "/global/cscratch1/sd/asdufek/pr" ⋯ 20 bytes ⋯ "/elpa-hsw/scripts/run_likwid.sh"
 "40000"
 "128"
 "128"
 "32"
 "512"
 "32"

In [57]:
show(df[df.jobId .== 44428415, 1:11], allcols=true)

1×11 DataFrame
 Row │ gresUsed          jobDerivedExitCode  uid     originCluster  minSwitchesAchieved  batchHost  argv                               burstBuffer  tresRequest                        endTime     packJobOffset 
     │ String?           Int64?              Int64?  String?        String?              String?    Array…?                            String?      String?                            Int64?      Int64?        
─────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1 │ craynetwork:2048                   0   92007  missing        true                 nid00792   Any["/global/cscratch1/sd/asdufe…  missing      1=32768,2=61865984,3=18446744073…  1627205772              0

In [61]:
show(df_sav[df_sav.jobId .== 44428415, 41:end], allcols=true)

7×4 DataFrame
 Row │ shifterImageRequest  originCluster  reservation  burstBuffer 
     │ String?              String?        String?      String?     
─────┼──────────────────────────────────────────────────────────────
   1 │ missing              missing        missing      missing     
   2 │ missing              missing        missing      missing     
   3 │ missing              missing        missing      missing     
   4 │ missing              missing        missing      missing     
   5 │ missing              missing        missing      missing     
   6 │ missing              missing        missing      missing     
   7 │ missing              missing        missing      missing     

In [104]:
e = filter(x->x["jobId"] == 44405291, sav)

1-element Vector{Dict{String, Any}}:
 Dict("startTime" => 1627103723, "jobDerivedExitCode" => 256, "submitTime" => 1626785981, "endTime" => 1627121281, "gresRequest" => "cpu=30,mem=3540G,node=30,billing=30", "tresRequest" => "1=1920,2=3624960,3=18446744073709551614,4=30,5=1920", "allocCpus" => 1920, "priority" => 69940, "batchHost" => "nid00813", "jobExitCode" => 0…)

In [105]:
e[1]["argv"]

2-element Vector{Any}:
 "/global/u1/v/vpa/project/jpt_no" ⋯ 76 bytes ⋯ "ptfcn/run_3ptfcn/batch_3ptcn.sh"
 "9"

In [21]:
isa_list(e[1]["argv"])

true

In [106]:
DataFrame(e)

1×33 DataFrame
 Row │ allocCpus  allocNodes  argv                               arrayJobId  a ⋯
     │ Int64      Int64       Array…                             Int64       I ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │      1920          30  Any["/global/u1/v/vpa/project/jp…           0    ⋯
                                                              29 columns omitted

In [109]:
e["argv"]

Base.RefValue{Vector{Any}}(Any["/global/u1/v/vpa/project/jpt_notebooks/Cosmology/Cosmo_GAN/repositories/cosmogan_pytorch/code/modules_threeptfcn/run_3ptfcn/batch_3ptcn.sh", "9"])

In [107]:
?Ref

search: Ref WeakRef prevfloat chopprefix UndefRefError GlobalRef quarterofyear



```
Ref{T}
```

An object that safely references data of type `T`. This type is guaranteed to point to valid, Julia-allocated memory of the correct type. The underlying data is protected from freeing by the garbage collector as long as the `Ref` itself is referenced.

In Julia, `Ref` objects are dereferenced (loaded or stored) with `[]`.

Creation of a `Ref` to a value `x` of type `T` is usually written `Ref(x)`. Additionally, for creating interior pointers to containers (such as Array or Ptr), it can be written `Ref(a, i)` for creating a reference to the `i`-th element of `a`.

`Ref{T}()` creates a reference to a value of type `T` without initialization. For a bitstype `T`, the value will be whatever currently resides in the memory allocated. For a non-bitstype `T`, the reference will be undefined and attempting to dereference it will result in an error, "UndefRefError: access to undefined reference".

To check if a `Ref` is an undefined reference, use [`isassigned(ref::RefValue)`](@ref). For example, `isassigned(Ref{T}())` is `false` if `T` is not a bitstype. If `T` is a bitstype, `isassigned(Ref{T}())` will always be true.

When passed as a `ccall` argument (either as a `Ptr` or `Ref` type), a `Ref` object will be converted to a native pointer to the data it references. For most `T`, or when converted to a `Ptr{Cvoid}`, this is a pointer to the object data. When `T` is an `isbits` type, this value may be safely mutated, otherwise mutation is strictly undefined behavior.

As a special case, setting `T = Any` will instead cause the creation of a pointer to the reference itself when converted to a `Ptr{Any}` (a `jl_value_t const* const*` if T is immutable, else a `jl_value_t *const *`). When converted to a `Ptr{Cvoid}`, it will still return a pointer to the data region as for any other `T`.

A `C_NULL` instance of `Ptr` can be passed to a `ccall` `Ref` argument to initialize it.

# Use in broadcasting

`Ref` is sometimes used in broadcasting in order to treat the referenced values as a scalar.

# Examples

```jldoctest
julia> Ref(5)
Base.RefValue{Int64}(5)

julia> isa.(Ref([1,2,3]), [Array, Dict, Int]) # Treat reference values as scalar during broadcasting
3-element BitVector:
 1
 0
 0

julia> Ref{Function}()  # Undefined reference to a non-bitstype, Function
Base.RefValue{Function}(#undef)

julia> try
           Ref{Function}()[] # Dereferencing an undefined reference will result in an error
       catch e
           println(e)
       end
UndefRefError()

julia> Ref{Int64}()[]; # A reference to a bitstype refers to an undetermined value if not given

julia> isassigned(Ref{Int64}()) # A reference to a bitstype is always assigned
true

julia> Ref{Int64}(0)[] == 0 # Explicitly give a value for a bitstype reference
true
```


In [12]:
r = sacct_get_jobs(
    account="lcls",
    starttime=DateTime(2021, 07, 23, 00, 00, 00),
    endtime=DateTime(2021, 07, 20, 00, 00, 00)
)

SlurmCLI.QueryResult(nothing, "sacct: error: Start time (2021-07-23T00:00:00) requested is after end time (2021-07-20T00:00:00).\n", 1)

In [11]:
r.result

Any[]

In [7]:
r.code

0

In [37]:
ENV["SCRATCH"]

"/global/cscratch1/sd/blaschke"

In [55]:
out, err, code = shell(`ls`);

In [57]:
println(out)

2020.ipynb
2021.ipynb
2021_urgent-hpc.ipynb
README.md
SlurmCLI
data
sacct.ipynb



In [60]:
split(out)

7-element Vector{SubString{String}}:
 "2020.ipynb"
 "2021.ipynb"
 "2021_urgent-hpc.ipynb"
 "README.md"
 "SlurmCLI"
 "data"
 "sacct.ipynb"

In [52]:
x.code

0

In [20]:
?shell

search: schedule searchsortedlast AbstractChannel

Couldn't find shell
Perhaps you meant help, show, sech, sec, secd, seek, sleep, step, isreal or all


No documentation found.

Binding `shell` does not exist.


In [31]:
for i in keys(sav[1])
    println(i, ' ', sav[1][i])
end

startTime 1628343143
jobDerivedExitCode 0
submitTime 1617414051
endTime 1628343181
gresRequest cpu=1,node=1,billing=1
tresRequest 1=64,2=120832,3=18446744073709551614,4=1,5=64
gresUsed craynetwork:4
priority 70005
batchHost nid00817
licenses cscratch1:1
packJobId 0
name 12380_278863_-7
jobId 41312612
allocNodes 1
jobAccount m3550
jobExitCode 0
allocCpus 64
resizing 0
uid 91828
argv Any["/global/u2/v/villotc/DES15K_SAPT23/calc_DES15K/natom5/12380_278863_-7.pbs"]
reboot 0
arrayTaskId 4294967294
timeLimit 900
cluster cori
stdinPath /dev/null
restartCnt 0
nodes nid00817
arrayJobId 0
features haswell
qos regular_1
workingDirectory /global/u2/v/villotc/DES15K_SAPT23/calc_DES15K/natom5
partition regular_hsw
packJobOffset 0


In [8]:
lx31_jobs = Dict(
    "lx31_1"  => sacct_get_jobs(lx31_1),
    "lx31_1a" => sacct_get_jobs(lx31_1a),
    "lx31_2"  => sacct_get_jobs(lx31_2)
)
lv07_jobs = Dict(
    "lv07_1" => sacct_get_jobs(lv07_1),
    "lv07_2" => sacct_get_jobs(lv07_2),
    "lv07_3" => sacct_get_jobs(lv07_3),
    "lv07_4" => sacct_get_jobs(lv07_4)
)
p203_jobs = Dict(
    "p203_1" => sacct_get_jobs(p203_1),
    "p203_2" => sacct_get_jobs(p203_2),
    "p203_3" => sacct_get_jobs(p203_3)
)

;

In [9]:
open(joinpath("data", "sacct", "lx31_jobs.json"), "w") do f
    JSON.print(f, lx31_jobs, 4)
end

open(joinpath("data", "sacct", "lv07_jobs.json"), "w") do f
    JSON.print(f, lv07_jobs, 4)
end

open(joinpath("data", "sacct", "p203_jobs.json"), "w") do f
    JSON.print(f, p203_jobs, 4)
end